export interface FileItem {
  id: string
  name: string
  type: "file" | "folder" | "app"
  icon?: string
  parent: string
  size?: string
  modified?: string
  extension?: string
  content?: string
  path?: string
  description?: string
}

export interface FileSystem {
  items: Record<string, FileItem>
  desktop: string[]
  beats: string[]
  documents: string[]
  downloads: string[]
  applications: string[]
  portfolio: string[]
  photography: string[]
  design: string[]
  video: string[]
  web: string[]
  marketing: string[]
  trash: string[]
}

export const initialFileSystem: FileSystem = {
  items: {
    "desktop-1": {
      id: "desktop-1",
      name: "Welcome to YUNG98 OS",
      type: "file",
      parent: "desktop",
      extension: "txt",
      size: "2 KB",
      modified: new Date().toLocaleDateString(),
      content:
        "Welcome to YUNG98 OS - your interactive beat world.\n\nTo get started:\n\n1. Open Finder and dig through the beat vault\n2. Open Safari to browse the beat store\n3. Launch YUNG98 Player for previews\n4. Send a licensing or custom request from Contact\n\nLock in your next record.",
    },
    "desktop-2": {
      id: "desktop-2",
      name: "YUNG98 Beat Vault",
      type: "folder",
      parent: "desktop",
      modified: new Date().toLocaleDateString(),
      icon: "/icons/portfolio-folder.webp",
    },
    "desktop-3": {
      id: "desktop-3",
      name: "Beat Licensing Guide",
      type: "file",
      parent: "desktop",
      extension: "pdf",
      size: "3.5 MB",
      modified: new Date().toLocaleDateString(),
      path: "/documents/services-brochure.pdf",
      icon: "/icons/pdf-icon.webp",
    },
    "desktop-4": {
      id: "desktop-4",
      name: "Beats",
      type: "folder",
      parent: "desktop",
      modified: new Date().toLocaleDateString(),
      icon: "/icons/folder.svg",
    },
    "documents-1": {
      id: "documents-1",
      name: "YUNG98 OS Deck",
      type: "file",
      parent: "documents",
      extension: "pdf",
      size: "2.5 MB",
      modified: new Date().toLocaleDateString(),
      path: "/documents/yung98-os-deck.pdf",
      icon: "/icons/pdf-icon.webp",
    },
    "documents-2": {
      id: "documents-2",
      name: "Artist Notes",
      type: "file",
      parent: "documents",
      extension: "txt",
      size: "4 KB",
      modified: new Date().toLocaleDateString(),
      content:
        '"The YUNG98 beat gave my single the exact energy I needed. Mix-ready and clean bounce out the box." - LEXA\n\n"Fast response, smooth license process, and the beat hit hard in clubs." - KRO\n\n"Custom work came back with crazy detail and space for vocals. I am locking in again." - NERO',
    },
    "documents-3": {
      id: "documents-3",
      name: "Beat Catalog",
      type: "file",
      parent: "documents",
      extension: "pdf",
      size: "1.8 MB",
      modified: new Date().toLocaleDateString(),
      path: "/documents/social-media-campaign.pdf",
      icon: "/icons/pdf-icon.webp",
    },
    "portfolio-1": {
      id: "portfolio-1",
      name: "Photography",
      type: "folder",
      parent: "portfolio",
      modified: new Date().toLocaleDateString(),
      icon: "/icons/photography-folder.webp",
    },
    "portfolio-2": {
      id: "portfolio-2",
      name: "Graphic Design",
      type: "folder",
      parent: "portfolio",
      modified: new Date().toLocaleDateString(),
      icon: "/icons/design-folder.webp",
    },
    "portfolio-3": {
      id: "portfolio-3",
      name: "Video Production",
      type: "folder",
      parent: "portfolio",
      modified: new Date().toLocaleDateString(),
      icon: "/icons/video-folder.webp",
    },
    "portfolio-4": {
      id: "portfolio-4",
      name: "Web Development",
      type: "folder",
      parent: "portfolio",
      modified: new Date().toLocaleDateString(),
      icon: "/icons/web-folder.webp",
    },
    "portfolio-5": {
      id: "portfolio-5",
      name: "Marketing",
      type: "folder",
      parent: "portfolio",
      modified: new Date().toLocaleDateString(),
      icon: "/icons/marketing-folder.webp",
    },
    "photography-1": {
      id: "photography-1",
      name: "Product Photography",
      type: "file",
      parent: "photography",
      extension: "jpg",
      size: "3.2 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/product-photography.jpg",
      description:
        "Professional product photography for e-commerce clients featuring premium lighting techniques and composition.",
    },
    "photography-2": {
      id: "photography-2",
      name: "Portrait Session",
      type: "file",
      parent: "photography",
      extension: "jpg",
      size: "2.8 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/portrait-session.jpg",
      description:
        "Corporate and personal portrait photography with professional retouching and multiple background options.",
    },
    "photography-3": {
      id: "photography-3",
      name: "Event Coverage",
      type: "file",
      parent: "photography",
      extension: "jpg",
      size: "4.1 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/event-coverage.jpg",
      description:
        "Comprehensive event photography coverage including candid shots, group photos, and venue documentation.",
    },
    "photography-4": {
      id: "photography-4",
      name: "Fashion Shoot",
      type: "file",
      parent: "photography",
      extension: "jpg",
      size: "3.7 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/fashion-shoot.jpg",
      description: "High-end fashion photography for catalogs, lookbooks, and marketing campaigns.",
    },
    "design-1": {
      id: "design-1",
      name: "Logo Design",
      type: "file",
      parent: "design",
      extension: "png",
      size: "1.5 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/logo-design.png",
      description: "Custom logo design with multiple iterations and comprehensive brand guidelines.",
    },
    "design-2": {
      id: "design-2",
      name: "Branding Package",
      type: "file",
      parent: "design",
      extension: "pdf",
      size: "5.2 MB",
      modified: new Date().toLocaleDateString(),
      path: "/documents/services-brochure.pdf",
      icon: "/icons/pdf-icon.webp",
      description: "Complete branding package including logo, color palette, typography, and usage guidelines.",
    },
    "design-3": {
      id: "design-3",
      name: "Print Materials",
      type: "file",
      parent: "design",
      extension: "jpg",
      size: "2.3 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/print-materials.jpg",
      description: "Business cards, brochures, flyers, and other print collateral designed for maximum impact.",
    },
    "design-4": {
      id: "design-4",
      name: "Packaging Design",
      type: "file",
      parent: "design",
      extension: "jpg",
      size: "2.8 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/packaging-design.jpg",
      description: "Product packaging design with 3D mockups and print-ready files.",
    },
    "video-1": {
      id: "video-1",
      name: "Commercial",
      type: "file",
      parent: "video",
      extension: "mp4",
      size: "18.5 MB",
      modified: new Date().toLocaleDateString(),
      path: "/videos/event-highlight.mp4",
      description: "30-second commercial spot with professional voiceover, music, and motion graphics.",
    },
    "video-2": {
      id: "video-2",
      name: "Corporate Video",
      type: "file",
      parent: "video",
      extension: "mp4",
      size: "22.7 MB",
      modified: new Date().toLocaleDateString(),
      path: "/videos/event-highlight.mp4",
      description: "Corporate overview video featuring interviews, b-roll, and professional narration.",
    },
    "video-3": {
      id: "video-3",
      name: "Social Media Content",
      type: "file",
      parent: "video",
      extension: "mp4",
      size: "12.3 MB",
      modified: new Date().toLocaleDateString(),
      path: "/videos/event-highlight.mp4",
      description: "Short-form video content optimized for Instagram, TikTok, and other social platforms.",
    },
    "video-4": {
      id: "video-4",
      name: "Event Highlight Reel",
      type: "file",
      parent: "video",
      extension: "mp4",
      size: "16.8 MB",
      modified: new Date().toLocaleDateString(),
      path: "/videos/event-highlight.mp4",
      description: "Dynamic highlight reel capturing the best moments from corporate and special events.",
    },
    "web-1": {
      id: "web-1",
      name: "E-commerce Website",
      type: "file",
      parent: "web",
      extension: "jpg",
      size: "2.4 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/ecommerce-website.jpg",
      description: "Fully responsive e-commerce website with product catalog, shopping cart, and payment processing.",
    },
    "web-2": {
      id: "web-2",
      name: "Corporate Website",
      type: "file",
      parent: "web",
      extension: "jpg",
      size: "1.9 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/corporate-website.jpg",
      description: "Professional corporate website with custom CMS, blog functionality, and contact forms.",
    },
    "web-3": {
      id: "web-3",
      name: "Portfolio Website",
      type: "file",
      parent: "web",
      extension: "jpg",
      size: "2.1 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/portfolio-website.jpg",
      description: "Creative portfolio website showcasing work with filterable galleries and smooth animations.",
    },
    "marketing-1": {
      id: "marketing-1",
      name: "Social Media Campaign",
      type: "file",
      parent: "marketing",
      extension: "pdf",
      size: "3.6 MB",
      modified: new Date().toLocaleDateString(),
      path: "/documents/social-media-campaign.pdf",
      icon: "/icons/pdf-icon.webp",
      description: "Comprehensive social media campaign strategy with content calendar and performance metrics.",
    },
    "marketing-2": {
      id: "marketing-2",
      name: "Email Marketing",
      type: "file",
      parent: "marketing",
      extension: "jpg",
      size: "1.8 MB",
      modified: new Date().toLocaleDateString(),
      path: "/images/email-marketing.jpg",
      description: "Email marketing templates and automation sequences with performance analytics.",
    },
    "marketing-3": {
      id: "marketing-3",
      name: "SEO Strategy",
      type: "file",
      parent: "marketing",
      extension: "pdf",
      size: "2.2 MB",
      modified: new Date().toLocaleDateString(),
      path: "/documents/seo-strategy.pdf",
      icon: "/icons/pdf-icon.webp",
      description:
        "Search engine optimization strategy with keyword research, content recommendations, and technical SEO audit.",
    },
    "applications-1": {
      id: "applications-1",
      name: "Safari",
      type: "app",
      parent: "applications",
      icon: "/icons/safari.webp",
      modified: new Date().toLocaleDateString(),
    },
    "applications-2": {
      id: "applications-2",
      name: "Terminal",
      type: "app",
      parent: "applications",
      icon: "/icons/terminal.webp",
      modified: new Date().toLocaleDateString(),
    },
    "applications-3": {
      id: "applications-3",
      name: "Music Player",
      type: "app",
      parent: "applications",
      icon: "/icons/music.svg",
      modified: new Date().toLocaleDateString(),
    },
    "applications-4": {
      id: "applications-4",
      name: "Contact Form",
      type: "app",
      parent: "applications",
      icon: "/icons/mail.webp",
      modified: new Date().toLocaleDateString(),
    },
  },
  desktop: ["desktop-1", "desktop-2", "desktop-3", "desktop-4"],
  beats: [],
  documents: ["documents-1", "documents-2", "documents-3"],
  downloads: [],
  applications: ["applications-1", "applications-2", "applications-3", "applications-4"],
  portfolio: ["portfolio-1", "portfolio-2", "portfolio-3", "portfolio-4", "portfolio-5"],
  photography: ["photography-1", "photography-2", "photography-3", "photography-4"],
  design: ["design-1", "design-2", "design-3", "design-4"],
  video: ["video-1", "video-2", "video-3", "video-4"],
  web: ["web-1", "web-2", "web-3"],
  marketing: ["marketing-1", "marketing-2", "marketing-3"],
  trash: [],
}
