import type { MenuItem } from "./menu-dropdown"

// Apple Menu - Common for all apps
export const appleMenu: MenuItem[] = [
  { id: "about", label: "About This Mac", action: () => console.log("About This Mac") },
  { id: "divider1", divider: true },
  { id: "preferences", label: "System Preferences...", action: () => console.log("System Preferences") },
  { id: "appstore", label: "App Store...", action: () => console.log("App Store") },
  { id: "divider2", divider: true },
  { id: "recent", label: "Recent Items", submenu: [{ id: "no-recent", label: "No Recent Items", disabled: true }] },
  { id: "divider3", divider: true },
  { id: "sleep", label: "Sleep", action: () => console.log("Sleep") },
  { id: "restart", label: "Restart...", action: () => console.log("Restart") },
  { id: "shutdown", label: "Shut Down...", action: () => console.log("Shut Down") },
  { id: "divider4", divider: true },
  { id: "logout", label: "Log Out Admin...", shortcut: "⇧⌘Q", action: () => console.log("Log Out") },
]

// Finder Menus
export const finderMenus = [
  {
    id: "finder",
    label: "Finder",
    items: [
      { id: "about", label: "About Finder", action: () => console.log("About Finder") },
      { id: "divider1", divider: true },
      { id: "preferences", label: "Preferences...", shortcut: "⌘,", action: () => console.log("Preferences") },
      { id: "divider2", divider: true },
      { id: "empty-trash", label: "Empty Trash...", action: () => console.log("Empty Trash") },
      { id: "divider3", divider: true },
      {
        id: "services",
        label: "Services",
        submenu: [{ id: "no-services", label: "No Services Apply", disabled: true }],
      },
      { id: "divider4", divider: true },
      { id: "hide-finder", label: "Hide Finder", shortcut: "⌘H", action: () => console.log("Hide Finder") },
      { id: "hide-others", label: "Hide Others", shortcut: "⌥⌘H", action: () => console.log("Hide Others") },
      { id: "show-all", label: "Show All", action: () => console.log("Show All") },
    ],
  },
  {
    id: "file",
    label: "File",
    items: [
      {
        id: "new-finder-window",
        label: "New Finder Window",
        shortcut: "⌘N",
        action: () => console.log("New Finder Window"),
      },
      { id: "new-folder", label: "New Folder", shortcut: "⇧⌘N", action: () => console.log("New Folder") },
      {
        id: "new-folder-with",
        label: "New Folder with Selection",
        shortcut: "⌥⌘N",
        action: () => console.log("New Folder with Selection"),
      },
      { id: "new-smart-folder", label: "New Smart Folder", action: () => console.log("New Smart Folder") },
      { id: "new-tab", label: "New Tab", shortcut: "⌘T", action: () => console.log("New Tab") },
      { id: "divider1", divider: true },
      { id: "open", label: "Open", shortcut: "⌘O", action: () => console.log("Open") },
      {
        id: "open-with",
        label: "Open With",
        submenu: [
          { id: "choose-app", label: "Choose Application...", action: () => console.log("Choose Application") },
        ],
      },
      { id: "divider2", divider: true },
      { id: "close-window", label: "Close Window", shortcut: "⌘W", action: () => console.log("Close Window") },
      { id: "get-info", label: "Get Info", shortcut: "⌘I", action: () => console.log("Get Info") },
      { id: "rename", label: "Rename", action: () => console.log("Rename") },
      { id: "divider3", divider: true },
      { id: "compress", label: "Compress", action: () => console.log("Compress") },
      { id: "divider4", divider: true },
      { id: "duplicate", label: "Duplicate", shortcut: "⌘D", action: () => console.log("Duplicate") },
      { id: "make-alias", label: "Make Alias", shortcut: "⌥⌘L", action: () => console.log("Make Alias") },
      { id: "quick-look", label: "Quick Look", shortcut: "⌘Y", action: () => console.log("Quick Look") },
      { id: "print", label: "Print", shortcut: "⌘P", action: () => console.log("Print") },
      { id: "divider5", divider: true },
      { id: "move-to-trash", label: "Move to Trash", shortcut: "⌘⌫", action: () => console.log("Move to Trash") },
      { id: "eject", label: "Eject", shortcut: "⌘E", action: () => console.log("Eject") },
      { id: "divider6", divider: true },
      { id: "find", label: "Find", shortcut: "⌘F", action: () => console.log("Find") },
      { id: "divider7", divider: true },
      { id: "tags", label: "Tags...", action: () => console.log("Tags") },
    ],
  },
  {
    id: "edit",
    label: "Edit",
    items: [
      { id: "undo", label: "Undo", shortcut: "⌘Z", action: () => console.log("Undo"), disabled: true },
      { id: "redo", label: "Redo", shortcut: "⇧⌘Z", action: () => console.log("Redo"), disabled: true },
      { id: "divider1", divider: true },
      { id: "cut", label: "Cut", shortcut: "⌘X", action: () => console.log("Cut"), disabled: true },
      { id: "copy", label: "Copy", shortcut: "⌘C", action: () => console.log("Copy"), disabled: true },
      { id: "paste", label: "Paste", shortcut: "⌘V", action: () => console.log("Paste"), disabled: true },
      { id: "select-all", label: "Select All", shortcut: "⌘A", action: () => console.log("Select All") },
      { id: "divider2", divider: true },
      { id: "show-clipboard", label: "Show Clipboard", action: () => console.log("Show Clipboard") },
      { id: "divider3", divider: true },
      {
        id: "start-dictation",
        label: "Start Dictation...",
        shortcut: "fn fn",
        action: () => console.log("Start Dictation"),
      },
      { id: "emoji", label: "Emoji & Symbols", shortcut: "⌃⌘Space", action: () => console.log("Emoji & Symbols") },
    ],
  },
  {
    id: "view",
    label: "View",
    items: [
      { id: "as-icons", label: "as Icons", shortcut: "⌘1", action: () => console.log("as Icons"), checked: true },
      { id: "as-list", label: "as List", shortcut: "⌘2", action: () => console.log("as List") },
      { id: "as-columns", label: "as Columns", shortcut: "⌘3", action: () => console.log("as Columns") },
      { id: "as-gallery", label: "as Gallery", shortcut: "⌘4", action: () => console.log("as Gallery") },
      { id: "divider1", divider: true },
      { id: "use-groups", label: "Use Groups", shortcut: "⌘J", action: () => console.log("Use Groups"), checked: true },
      {
        id: "sort-by",
        label: "Sort By",
        submenu: [
          { id: "name", label: "Name", action: () => console.log("Sort by Name"), checked: true },
          { id: "kind", label: "Kind", action: () => console.log("Sort by Kind") },
          { id: "date-added", label: "Date Added", action: () => console.log("Sort by Date Added") },
          { id: "date-modified", label: "Date Modified", action: () => console.log("Sort by Date Modified") },
          { id: "size", label: "Size", action: () => console.log("Sort by Size") },
          { id: "tags", label: "Tags", action: () => console.log("Sort by Tags") },
        ],
      },
      { id: "divider2", divider: true },
      { id: "hide-sidebar", label: "Hide Sidebar", shortcut: "⌥⌘S", action: () => console.log("Hide Sidebar") },
      { id: "hide-preview", label: "Hide Preview", shortcut: "⇧⌘P", action: () => console.log("Hide Preview") },
      { id: "divider3", divider: true },
      { id: "hide-toolbar", label: "Hide Toolbar", shortcut: "⌥⌘T", action: () => console.log("Hide Toolbar") },
      { id: "show-all-tabs", label: "Show All Tabs", shortcut: "⇧⌘\\", action: () => console.log("Show All Tabs") },
      { id: "hide-tab-bar", label: "Hide Tab Bar", shortcut: "⇧⌘T", action: () => console.log("Hide Tab Bar") },
      { id: "hide-path-bar", label: "Hide Path Bar", shortcut: "⌥⌘P", action: () => console.log("Hide Path Bar") },
      { id: "hide-status-bar", label: "Hide Status Bar", shortcut: "⌘/", action: () => console.log("Hide Status Bar") },
      { id: "divider4", divider: true },
      { id: "customize-toolbar", label: "Customize Toolbar...", action: () => console.log("Customize Toolbar") },
      { id: "divider5", divider: true },
      {
        id: "show-view-options",
        label: "Show View Options",
        shortcut: "⌘J",
        action: () => console.log("Show View Options"),
      },
    ],
  },
  {
    id: "go",
    label: "Go",
    items: [
      { id: "back", label: "Back", shortcut: "⌘[", action: () => console.log("Back"), disabled: true },
      { id: "forward", label: "Forward", shortcut: "⌘]", action: () => console.log("Forward"), disabled: true },
      {
        id: "enclosing-folder",
        label: "Enclosing Folder",
        shortcut: "⌘↑",
        action: () => console.log("Enclosing Folder"),
      },
      { id: "divider1", divider: true },
      { id: "recents", label: "Recents", shortcut: "⇧⌘F", action: () => console.log("Recents") },
      { id: "documents", label: "Documents", shortcut: "⇧⌘O", action: () => console.log("Documents") },
      { id: "desktop", label: "Desktop", shortcut: "⇧⌘D", action: () => console.log("Desktop") },
      { id: "downloads", label: "Downloads", shortcut: "⌥⌘L", action: () => console.log("Downloads") },
      { id: "home", label: "Home", shortcut: "⇧⌘H", action: () => console.log("Home") },
      { id: "computer", label: "Computer", shortcut: "⇧⌘C", action: () => console.log("Computer") },
      { id: "airdrop", label: "AirDrop", shortcut: "⇧⌘R", action: () => console.log("AirDrop") },
      { id: "network", label: "Network", shortcut: "⇧⌘K", action: () => console.log("Network") },
      { id: "icloud", label: "iCloud Drive", shortcut: "⇧⌘I", action: () => console.log("iCloud Drive") },
      { id: "applications", label: "Applications", shortcut: "⇧⌘A", action: () => console.log("Applications") },
      { id: "utilities", label: "Utilities", shortcut: "⇧⌘U", action: () => console.log("Utilities") },
      { id: "divider2", divider: true },
      { id: "go-to-folder", label: "Go to Folder...", shortcut: "⇧⌘G", action: () => console.log("Go to Folder") },
      {
        id: "connect-to-server",
        label: "Connect to Server...",
        shortcut: "⌘K",
        action: () => console.log("Connect to Server"),
      },
    ],
  },
  {
    id: "window",
    label: "Window",
    items: [
      { id: "minimize", label: "Minimize", shortcut: "⌘M", action: () => console.log("Minimize") },
      { id: "zoom", label: "Zoom", action: () => console.log("Zoom") },
      {
        id: "cycle",
        label: "Cycle Through Windows",
        shortcut: "⌘`",
        action: () => console.log("Cycle Through Windows"),
      },
      { id: "divider1", divider: true },
      { id: "bring-all-to-front", label: "Bring All to Front", action: () => console.log("Bring All to Front") },
      { id: "divider2", divider: true },
      { id: "finder", label: "Finder", checked: true, action: () => console.log("Show Finder") },
    ],
  },
  {
    id: "help",
    label: "Help",
    items: [
      { id: "finder-help", label: "macOS Help", action: () => console.log("macOS Help") },
      { id: "divider1", divider: true },
      { id: "see-whats-new", label: "See What's New in macOS", action: () => console.log("See What's New in macOS") },
      {
        id: "new-to-mac",
        label: "New to Mac? Tour the Basics",
        action: () => console.log("New to Mac? Tour the Basics"),
      },
      { id: "divider2", divider: true },
      { id: "keyboard-shortcuts", label: "Keyboard Shortcuts", action: () => console.log("Keyboard Shortcuts") },
    ],
  },
]

// Safari Menus
export const safariMenus = [
  {
    id: "safari",
    label: "Safari",
    items: [
      { id: "about", label: "About Safari", action: () => console.log("About Safari") },
      { id: "divider1", divider: true },
      { id: "preferences", label: "Preferences...", shortcut: "⌘,", action: () => console.log("Preferences") },
      { id: "divider2", divider: true },
      { id: "clear-history", label: "Clear History...", action: () => console.log("Clear History") },
      { id: "divider3", divider: true },
      {
        id: "services",
        label: "Services",
        submenu: [{ id: "no-services", label: "No Services Apply", disabled: true }],
      },
      { id: "divider4", divider: true },
      { id: "hide-safari", label: "Hide Safari", shortcut: "⌘H", action: () => console.log("Hide Safari") },
      { id: "hide-others", label: "Hide Others", shortcut: "⌥⌘H", action: () => console.log("Hide Others") },
      { id: "show-all", label: "Show All", action: () => console.log("Show All") },
      { id: "divider5", divider: true },
      { id: "quit", label: "Quit Safari", shortcut: "⌘Q", action: () => console.log("Quit Safari") },
    ],
  },
  {
    id: "file",
    label: "File",
    items: [
      { id: "new-window", label: "New Window", shortcut: "⌘N", action: () => console.log("New Window") },
      {
        id: "new-private-window",
        label: "New Private Window",
        shortcut: "⇧⌘N",
        action: () => console.log("New Private Window"),
      },
      { id: "new-tab", label: "New Tab", shortcut: "⌘T", action: () => console.log("New Tab") },
      { id: "divider1", divider: true },
      { id: "open-file", label: "Open File...", shortcut: "⌘O", action: () => console.log("Open File") },
      { id: "open-location", label: "Open Location...", shortcut: "⌘L", action: () => console.log("Open Location") },
      { id: "divider2", divider: true },
      { id: "close-window", label: "Close Window", shortcut: "⌘W", action: () => console.log("Close Window") },
      { id: "close-tab", label: "Close Tab", shortcut: "⌘W", action: () => console.log("Close Tab") },
      { id: "save-as", label: "Save As...", shortcut: "⇧⌘S", action: () => console.log("Save As") },
      { id: "divider3", divider: true },
      {
        id: "share",
        label: "Share",
        submenu: [
          { id: "email-link", label: "Email This Page", action: () => console.log("Email This Page") },
          { id: "messages", label: "Messages", action: () => console.log("Messages") },
          { id: "airdrop", label: "AirDrop", action: () => console.log("AirDrop") },
          { id: "notes", label: "Notes", action: () => console.log("Notes") },
          { id: "reminders", label: "Reminders", action: () => console.log("Reminders") },
        ],
      },
      { id: "divider4", divider: true },
      { id: "print", label: "Print...", shortcut: "⌘P", action: () => console.log("Print") },
    ],
  },
  {
    id: "edit",
    label: "Edit",
    items: [
      { id: "undo", label: "Undo", shortcut: "⌘Z", action: () => console.log("Undo"), disabled: true },
      { id: "redo", label: "Redo", shortcut: "⇧⌘Z", action: () => console.log("Redo"), disabled: true },
      { id: "divider1", divider: true },
      { id: "cut", label: "Cut", shortcut: "⌘X", action: () => console.log("Cut"), disabled: true },
      { id: "copy", label: "Copy", shortcut: "⌘C", action: () => console.log("Copy") },
      { id: "paste", label: "Paste", shortcut: "⌘V", action: () => console.log("Paste") },
      {
        id: "paste-and-match-style",
        label: "Paste and Match Style",
        shortcut: "⌥⇧⌘V",
        action: () => console.log("Paste and Match Style"),
      },
      { id: "select-all", label: "Select All", shortcut: "⌘A", action: () => console.log("Select All") },
      { id: "divider2", divider: true },
      {
        id: "find",
        label: "Find",
        submenu: [
          { id: "find", label: "Find...", shortcut: "⌘F", action: () => console.log("Find") },
          { id: "find-next", label: "Find Next", shortcut: "⌘G", action: () => console.log("Find Next") },
          { id: "find-previous", label: "Find Previous", shortcut: "⇧⌘G", action: () => console.log("Find Previous") },
          {
            id: "use-selection",
            label: "Use Selection for Find",
            shortcut: "⌘E",
            action: () => console.log("Use Selection for Find"),
          },
          {
            id: "jump-to-selection",
            label: "Jump to Selection",
            shortcut: "⌘J",
            action: () => console.log("Jump to Selection"),
          },
        ],
      },
      { id: "divider3", divider: true },
      {
        id: "spelling",
        label: "Spelling and Grammar",
        submenu: [
          {
            id: "show",
            label: "Show Spelling and Grammar",
            shortcut: "⌘:",
            action: () => console.log("Show Spelling and Grammar"),
          },
          {
            id: "check-document",
            label: "Check Document Now",
            shortcut: "⌘;",
            action: () => console.log("Check Document Now"),
          },
          { id: "divider1", divider: true },
          {
            id: "check-spelling",
            label: "Check Spelling While Typing",
            action: () => console.log("Check Spelling While Typing"),
            checked: true,
          },
          {
            id: "check-grammar",
            label: "Check Grammar With Spelling",
            action: () => console.log("Check Grammar With Spelling"),
            checked: true,
          },
          {
            id: "correct-spelling",
            label: "Correct Spelling Automatically",
            action: () => console.log("Correct Spelling Automatically"),
            checked: true,
          },
        ],
      },
      {
        id: "substitutions",
        label: "Substitutions",
        submenu: [
          { id: "show-substitutions", label: "Show Substitutions", action: () => console.log("Show Substitutions") },
          { id: "divider1", divider: true },
          { id: "smart-quotes", label: "Smart Quotes", action: () => console.log("Smart Quotes"), checked: true },
          { id: "smart-dashes", label: "Smart Dashes", action: () => console.log("Smart Dashes"), checked: true },
          {
            id: "text-replacement",
            label: "Text Replacement",
            action: () => console.log("Text Replacement"),
            checked: true,
          },
        ],
      },
      {
        id: "speech",
        label: "Speech",
        submenu: [
          { id: "start-speaking", label: "Start Speaking", action: () => console.log("Start Speaking") },
          { id: "stop-speaking", label: "Stop Speaking", action: () => console.log("Stop Speaking"), disabled: true },
        ],
      },
    ],
  },
  {
    id: "view",
    label: "View",
    items: [
      {
        id: "always-show-toolbar",
        label: "Always Show Toolbar in Full Screen",
        action: () => console.log("Always Show Toolbar in Full Screen"),
        checked: true,
      },
      {
        id: "always-show-tab-bar",
        label: "Always Show Tab Bar",
        action: () => console.log("Always Show Tab Bar"),
        checked: true,
      },
      {
        id: "show-favorites-bar",
        label: "Show Favorites Bar",
        shortcut: "⇧⌘B",
        action: () => console.log("Show Favorites Bar"),
        checked: true,
      },
      { id: "show-status-bar", label: "Show Status Bar", action: () => console.log("Show Status Bar") },
      { id: "divider1", divider: true },
      { id: "stop", label: "Stop", shortcut: "⌘.", action: () => console.log("Stop") },
      { id: "reload", label: "Reload Page", shortcut: "⌘R", action: () => console.log("Reload Page") },
      { id: "divider2", divider: true },
      {
        id: "text-size",
        label: "Text Size",
        submenu: [
          { id: "bigger", label: "Make Text Bigger", shortcut: "⌘+", action: () => console.log("Make Text Bigger") },
          { id: "smaller", label: "Make Text Smaller", shortcut: "⌘-", action: () => console.log("Make Text Smaller") },
          { id: "default", label: "Actual Size", shortcut: "⌘0", action: () => console.log("Actual Size") },
        ],
      },
      { id: "divider3", divider: true },
      {
        id: "enter-full-screen",
        label: "Enter Full Screen",
        shortcut: "⌃⌘F",
        action: () => console.log("Enter Full Screen"),
      },
    ],
  },
  {
    id: "history",
    label: "History",
    items: [
      { id: "back", label: "Back", shortcut: "⌘[", action: () => console.log("Back"), disabled: true },
      { id: "forward", label: "Forward", shortcut: "⌘]", action: () => console.log("Forward"), disabled: true },
      { id: "divider1", divider: true },
      { id: "home", label: "Home", action: () => console.log("Home") },
      { id: "divider2", divider: true },
      { id: "show-history", label: "Show All History", shortcut: "⌥⌘2", action: () => console.log("Show All History") },
      { id: "clear-history", label: "Clear History...", action: () => console.log("Clear History") },
      { id: "divider3", divider: true },
      {
        id: "reopen-last-closed-tab",
        label: "Reopen Last Closed Tab",
        shortcut: "⇧⌘T",
        action: () => console.log("Reopen Last Closed Tab"),
        disabled: true,
      },
      {
        id: "reopen-last-closed-window",
        label: "Reopen Last Closed Window",
        action: () => console.log("Reopen Last Closed Window"),
        disabled: true,
      },
      { id: "divider4", divider: true },
      {
        id: "recently-closed",
        label: "Recently Closed",
        submenu: [{ id: "no-recently-closed", label: "No Recently Closed Items", disabled: true }],
      },
    ],
  },
  {
    id: "bookmarks",
    label: "Bookmarks",
    items: [
      { id: "add-bookmark", label: "Add Bookmark...", shortcut: "⌘D", action: () => console.log("Add Bookmark") },
      {
        id: "add-bookmarks-for-tabs",
        label: "Add Bookmarks for These Tabs...",
        action: () => console.log("Add Bookmarks for These Tabs"),
      },
      { id: "divider1", divider: true },
      { id: "show-bookmarks", label: "Show Bookmarks", shortcut: "⌥⌘1", action: () => console.log("Show Bookmarks") },
      {
        id: "show-bookmarks-sidebar",
        label: "Show Bookmarks Sidebar",
        shortcut: "⇧⌘L",
        action: () => console.log("Show Bookmarks Sidebar"),
      },
      { id: "divider2", divider: true },
      {
        id: "bookmarks-menu",
        label: "Bookmarks Menu",
        submenu: [
          { id: "about-bookmarks", label: "About Bookmarks Menu", disabled: true },
          { id: "divider1", divider: true },
          { id: "apple", label: "Apple", action: () => console.log("Apple Bookmark") },
          { id: "icloud", label: "iCloud", action: () => console.log("iCloud Bookmark") },
          { id: "mac", label: "Mac", action: () => console.log("Mac Bookmark") },
        ],
      },
    ],
  },
  {
    id: "window",
    label: "Window",
    items: [
      { id: "minimize", label: "Minimize", shortcut: "⌘M", action: () => console.log("Minimize") },
      { id: "zoom", label: "Zoom", action: () => console.log("Zoom") },
      {
        id: "cycle",
        label: "Cycle Through Windows",
        shortcut: "⌘`",
        action: () => console.log("Cycle Through Windows"),
      },
      { id: "divider1", divider: true },
      { id: "show-downloads", label: "Downloads", shortcut: "⌥⌘L", action: () => console.log("Show Downloads") },
      { id: "divider2", divider: true },
      { id: "bring-all-to-front", label: "Bring All to Front", action: () => console.log("Bring All to Front") },
      { id: "divider3", divider: true },
      { id: "safari", label: "Safari", checked: true, action: () => console.log("Show Safari") },
    ],
  },
  {
    id: "help",
    label: "Help",
    items: [
      { id: "safari-help", label: "Safari Help", action: () => console.log("Safari Help") },
      { id: "divider1", divider: true },
      { id: "report-website-issue", label: "Report Website Issue", action: () => console.log("Report Website Issue") },
      {
        id: "report-fraud",
        label: "Report Fraudulent Website",
        action: () => console.log("Report Fraudulent Website"),
      },
    ],
  },
]

// Terminal Menus
export const terminalMenus = [
  {
    id: "terminal",
    label: "Terminal",
    items: [
      { id: "about", label: "About Terminal", action: () => console.log("About Terminal") },
      { id: "divider1", divider: true },
      { id: "preferences", label: "Preferences...", shortcut: "⌘,", action: () => console.log("Preferences") },
      { id: "divider2", divider: true },
      {
        id: "services",
        label: "Services",
        submenu: [{ id: "no-services", label: "No Services Apply", disabled: true }],
      },
      { id: "divider3", divider: true },
      { id: "hide-terminal", label: "Hide Terminal", shortcut: "⌘H", action: () => console.log("Hide Terminal") },
      { id: "hide-others", label: "Hide Others", shortcut: "⌥⌘H", action: () => console.log("Hide Others") },
      { id: "show-all", label: "Show All", action: () => console.log("Show All") },
      { id: "divider4", divider: true },
      { id: "quit", label: "Quit Terminal", shortcut: "⌘Q", action: () => console.log("Quit Terminal") },
    ],
  },
  {
    id: "shell",
    label: "Shell",
    items: [
      { id: "new-window", label: "New Window", shortcut: "⌘N", action: () => console.log("New Window") },
      { id: "new-tab", label: "New Tab", shortcut: "⌘T", action: () => console.log("New Tab") },
      { id: "divider1", divider: true },
      { id: "close-window", label: "Close Window", shortcut: "⇧⌘W", action: () => console.log("Close Window") },
      { id: "close-tab", label: "Close Tab", shortcut: "⌘W", action: () => console.log("Close Tab") },
      { id: "divider2", divider: true },
      { id: "export-text-as", label: "Export Text As...", action: () => console.log("Export Text As") },
      {
        id: "export-selected-text-as",
        label: "Export Selected Text As...",
        action: () => console.log("Export Selected Text As"),
        disabled: true,
      },
      { id: "show-info", label: "Show Info", shortcut: "⌘I", action: () => console.log("Show Info") },
      { id: "divider3", divider: true },
      { id: "print", label: "Print...", shortcut: "⌘P", action: () => console.log("Print") },
    ],
  },
  {
    id: "edit",
    label: "Edit",
    items: [
      { id: "undo", label: "Undo", shortcut: "⌘Z", action: () => console.log("Undo"), disabled: true },
      { id: "redo", label: "Redo", shortcut: "⇧⌘Z", action: () => console.log("Redo"), disabled: true },
      { id: "divider1", divider: true },
      { id: "cut", label: "Cut", shortcut: "⌘X", action: () => console.log("Cut"), disabled: true },
      { id: "copy", label: "Copy", shortcut: "⌘C", action: () => console.log("Copy") },
      { id: "paste", label: "Paste", shortcut: "⌘V", action: () => console.log("Paste") },
      { id: "paste-selection", label: "Paste Selection", action: () => console.log("Paste Selection") },
      { id: "select-all", label: "Select All", shortcut: "⌘A", action: () => console.log("Select All") },
      { id: "divider2", divider: true },
      {
        id: "find",
        label: "Find",
        submenu: [
          { id: "find", label: "Find...", shortcut: "⌘F", action: () => console.log("Find") },
          { id: "find-next", label: "Find Next", shortcut: "⌘G", action: () => console.log("Find Next") },
          { id: "find-previous", label: "Find Previous", shortcut: "⇧⌘G", action: () => console.log("Find Previous") },
          {
            id: "use-selection",
            label: "Use Selection for Find",
            shortcut: "⌘E",
            action: () => console.log("Use Selection for Find"),
          },
          {
            id: "jump-to-selection",
            label: "Jump to Selection",
            shortcut: "⌘J",
            action: () => console.log("Jump to Selection"),
          },
        ],
      },
      { id: "divider3", divider: true },
      {
        id: "mark",
        label: "Mark",
        submenu: [
          { id: "mark-prompt", label: "Mark Prompt", action: () => console.log("Mark Prompt") },
          { id: "divider1", divider: true },
          { id: "clear-mark", label: "Clear Mark", action: () => console.log("Clear Mark") },
        ],
      },
      { id: "divider4", divider: true },
      {
        id: "start-dictation",
        label: "Start Dictation...",
        shortcut: "fn fn",
        action: () => console.log("Start Dictation"),
      },
      { id: "emoji", label: "Emoji & Symbols", shortcut: "⌃⌘Space", action: () => console.log("Emoji & Symbols") },
    ],
  },
  {
    id: "view",
    label: "View",
    items: [
      { id: "show-toolbar", label: "Show Toolbar", action: () => console.log("Show Toolbar"), checked: true },
      { id: "customize-toolbar", label: "Customize Toolbar...", action: () => console.log("Customize Toolbar") },
      { id: "divider1", divider: true },
      {
        id: "line-wrap",
        label: "Allow Line Wrapping",
        action: () => console.log("Allow Line Wrapping"),
        checked: true,
      },
      { id: "divider2", divider: true },
      { id: "default-font", label: "Use Default Font", shortcut: "⌘0", action: () => console.log("Use Default Font") },
      { id: "bigger", label: "Bigger", shortcut: "⌘+", action: () => console.log("Bigger") },
      { id: "smaller", label: "Smaller", shortcut: "⌘-", action: () => console.log("Smaller") },
      { id: "divider3", divider: true },
      { id: "show-tab-bar", label: "Show Tab Bar", action: () => console.log("Show Tab Bar"), checked: true },
      { id: "divider4", divider: true },
      {
        id: "enter-full-screen",
        label: "Enter Full Screen",
        shortcut: "⌃⌘F",
        action: () => console.log("Enter Full Screen"),
      },
    ],
  },
  {
    id: "window",
    label: "Window",
    items: [
      { id: "minimize", label: "Minimize", shortcut: "⌘M", action: () => console.log("Minimize") },
      { id: "zoom", label: "Zoom", action: () => console.log("Zoom") },
      {
        id: "cycle",
        label: "Cycle Through Windows",
        shortcut: "⌘`",
        action: () => console.log("Cycle Through Windows"),
      },
      { id: "divider1", divider: true },
      { id: "bring-all-to-front", label: "Bring All to Front", action: () => console.log("Bring All to Front") },
      { id: "divider2", divider: true },
      { id: "terminal", label: "Terminal", checked: true, action: () => console.log("Show Terminal") },
    ],
  },
  {
    id: "help",
    label: "Help",
    items: [
      { id: "terminal-help", label: "Terminal Help", action: () => console.log("Terminal Help") },
      { id: "divider1", divider: true },
      {
        id: "command-line-tools",
        label: "Command Line Developer Tools",
        submenu: [
          { id: "install", label: "Install", action: () => console.log("Install Command Line Tools") },
          { id: "uninstall", label: "Uninstall", action: () => console.log("Uninstall Command Line Tools") },
        ],
      },
    ],
  },
]

// System Preferences Menus
export const systemPreferencesMenus = [
  {
    id: "system-preferences",
    label: "System Preferences",
    items: [
      { id: "about", label: "About System Preferences", action: () => console.log("About System Preferences") },
      { id: "divider1", divider: true },
      {
        id: "services",
        label: "Services",
        submenu: [{ id: "no-services", label: "No Services Apply", disabled: true }],
      },
      { id: "divider2", divider: true },
      {
        id: "hide-system-preferences",
        label: "Hide System Preferences",
        shortcut: "⌘H",
        action: () => console.log("Hide System Preferences"),
      },
      { id: "hide-others", label: "Hide Others", shortcut: "⌥⌘H", action: () => console.log("Hide Others") },
      { id: "show-all", label: "Show All", action: () => console.log("Show All") },
      { id: "divider3", divider: true },
      {
        id: "quit",
        label: "Quit System Preferences",
        shortcut: "⌘Q",
        action: () => console.log("Quit System Preferences"),
      },
    ],
  },
  {
    id: "view",
    label: "View",
    items: [
      { id: "as-icons", label: "as Icons", action: () => console.log("View as Icons"), checked: true },
      { id: "as-list", label: "as List", action: () => console.log("View as List") },
      {
        id: "organize-by",
        label: "Organize by Categories",
        action: () => console.log("Organize by Categories"),
        checked: true,
      },
      { id: "divider1", divider: true },
      { id: "customize", label: "Customize...", action: () => console.log("Customize") },
      { id: "divider2", divider: true },
      {
        id: "show-all",
        label: "Show All Preferences",
        action: () => console.log("Show All Preferences"),
        checked: true,
      },
    ],
  },
  {
    id: "window",
    label: "Window",
    items: [
      { id: "minimize", label: "Minimize", shortcut: "⌘M", action: () => console.log("Minimize") },
      { id: "zoom", label: "Zoom", action: () => console.log("Zoom") },
      {
        id: "cycle",
        label: "Cycle Through Windows",
        shortcut: "⌘`",
        action: () => console.log("Cycle Through Windows"),
      },
      { id: "divider1", divider: true },
      { id: "bring-all-to-front", label: "Bring All to Front", action: () => console.log("Bring All to Front") },
      { id: "divider2", divider: true },
      {
        id: "system-preferences",
        label: "System Preferences",
        checked: true,
        action: () => console.log("Show System Preferences"),
      },
    ],
  },
  {
    id: "help",
    label: "Help",
    items: [
      {
        id: "system-preferences-help",
        label: "System Preferences Help",
        action: () => console.log("System Preferences Help"),
      },
    ],
  },
]

// Default menus when no window is active
export const defaultMenus = [
  {
    id: "finder",
    label: "Finder",
    items: [
      { id: "about", label: "About Finder", action: () => console.log("About Finder") },
      { id: "divider1", divider: true },
      { id: "preferences", label: "Preferences...", shortcut: "⌘,", action: () => console.log("Preferences") },
      { id: "divider2", divider: true },
      { id: "empty-trash", label: "Empty Trash...", action: () => console.log("Empty Trash") },
      { id: "divider3", divider: true },
      {
        id: "services",
        label: "Services",
        submenu: [{ id: "no-services", label: "No Services Apply", disabled: true }],
      },
    ],
  },
  {
    id: "file",
    label: "File",
    items: [
      {
        id: "new-finder-window",
        label: "New Finder Window",
        shortcut: "⌘N",
        action: () => console.log("New Finder Window"),
      },
      { id: "new-folder", label: "New Folder", shortcut: "⇧⌘N", action: () => console.log("New Folder") },
      { id: "divider1", divider: true },
      {
        id: "close-window",
        label: "Close Window",
        shortcut: "⌘W",
        action: () => console.log("Close Window"),
        disabled: true,
      },
    ],
  },
  {
    id: "edit",
    label: "Edit",
    items: [
      { id: "undo", label: "Undo", shortcut: "⌘Z", action: () => console.log("Undo"), disabled: true },
      { id: "redo", label: "Redo", shortcut: "⇧⌘Z", action: () => console.log("Redo"), disabled: true },
      { id: "divider1", divider: true },
      { id: "cut", label: "Cut", shortcut: "⌘X", action: () => console.log("Cut"), disabled: true },
      { id: "copy", label: "Copy", shortcut: "⌘C", action: () => console.log("Copy"), disabled: true },
      { id: "paste", label: "Paste", shortcut: "⌘V", action: () => console.log("Paste"), disabled: true },
      {
        id: "select-all",
        label: "Select All",
        shortcut: "⌘A",
        action: () => console.log("Select All"),
        disabled: true,
      },
    ],
  },
  {
    id: "view",
    label: "View",
    items: [
      { id: "as-icons", label: "as Icons", shortcut: "⌘1", action: () => console.log("as Icons"), disabled: true },
      { id: "as-list", label: "as List", shortcut: "⌘2", action: () => console.log("as List"), disabled: true },
      {
        id: "as-columns",
        label: "as Columns",
        shortcut: "⌘3",
        action: () => console.log("as Columns"),
        disabled: true,
      },
      {
        id: "as-gallery",
        label: "as Gallery",
        shortcut: "⌘4",
        action: () => console.log("as Gallery"),
        disabled: true,
      },
    ],
  },
  {
    id: "window",
    label: "Window",
    items: [
      { id: "minimize", label: "Minimize", shortcut: "⌘M", action: () => console.log("Minimize"), disabled: true },
      { id: "zoom", label: "Zoom", action: () => console.log("Zoom"), disabled: true },
      { id: "divider1", divider: true },
      { id: "bring-all-to-front", label: "Bring All to Front", action: () => console.log("Bring All to Front") },
    ],
  },
  {
    id: "help",
    label: "Help",
    items: [{ id: "macos-help", label: "macOS Help", action: () => console.log("macOS Help") }],
  },
]

